<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />  
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
   
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
       
    <link href="<?php echo $this->basePath()?>/css/admin/bootstrap.min.css" rel="stylesheet" />   
    <link href="<?php echo $this->basePath()?>/css/admin/light_bootstrap_dashboard.css" rel="stylesheet" />
    <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/admin/style.css">
     <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/global.js'))
                ->prependFile($this->basePath('js/jquery.mCustomScrollbar.min.js'))
                
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/popper.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/fontawesome.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    
    <script src="<?php echo $this->basePath()?>/js/admin/light_bootstrap_dashboard.js"></script>
    <script type="text/javascript" charset="utf8" src="<?php echo $this->basePath();?>/js/jquery.dataTables.min.js"></script>
    
    
     

    
    <script type="text/javascript" charset="utf8" src="<?php echo $this->basePath();?>/js/jquery.dataTables.min.js"></script>
<script>
    var BASE_URL = "<?php echo $this->basePath(); ?>";
</script>
</head>
<body>
    <div class="wrapper">
        <div class="sidebar">          
            <div class="sidebar-wrapper">               
                <div class="menu-list">
                    <ul class="nav m-0 mCustomScrollbar" data-mcs-theme="minimal-dark">

                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 1) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link" rel="canonical"   href="<?php echo $this->basePath(); ?>/admin/admin-home">
                             
                                <span class="text-capitalize ">HOME</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                        if (isset($activeTab) && $activeTab == 15) {
                            echo "active";
                        }
                        ?>" >
                            <a class="nav-link"  href="<?php echo $this->basePath(); ?>/admin/advisor">

                                <span class="text-capitalize ">ADVISORS</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 2) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  href="<?php echo $this->basePath(); ?>/admin/add-about-us">
                   
                                <span class="text-capitalize ">ABOUT US</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                        if (isset($activeTab) && $activeTab == 10) {
                            echo "active";
                        }
                        ?>" >
                            <a class="nav-link"  href="<?php echo $this->basePath(); ?>/admin/statistics">

                                <span class="text-capitalize ">STATISTICS</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                        if (isset($activeTab) && $activeTab == 14) {
                            echo "active";
                        }
                        ?>" >
                            <a class="nav-link"  href="<?php echo $this->basePath(); ?>/admin/executive">

                                <span class="text-capitalize ">EXECUTIVES</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 11) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  href="<?php echo $this->basePath(); ?>/admin/our-team">
                   
                                <span class="text-capitalize ">OUR TEAM</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 8) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  href="<?php echo $this->basePath(); ?>/admin/add-how-it-works">
                   
                                <span class="text-capitalize ">HOW IT W0RKS</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 9) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  href="<?php echo $this->basePath(); ?>/admin/features">
                   
                                <span class="text-capitalize ">FEATURES</span>
                            </a>
                        </li>
                        <!--<li class="nav-item <?php
/*                                    if (isset($activeTab) && $activeTab == 10) {
                                        echo "active";
                                    }
                                    */?>" >
                            <a class="nav-link"  href="<?php /*echo $this->basePath(); */?>/admin/statistics">
                   
                                <span class="text-capitalize ">STATISTICS</span>
                            </a>
                        </li>-->
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 3) 
                                    {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  rel="canonical"  href="<?php echo $this->basePath(); ?>/admin/service">
                    
                                <span class="text-capitalize ">SERVICES</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 4) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  rel="canonical"  href="<?php echo $this->basePath(); ?>/admin/blog">
                   
                                <span class="text-capitalize ">BLOGS</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 5) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"   rel="canonical" href="<?php echo $this->basePath(); ?>/admin/admin-gallery">
                   
                                <span class="text-capitalize ">GALLERY</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 6) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"   rel="canonical" href="<?php echo $this->basePath(); ?>/admin/career">
                   
                                <span class="text-capitalize ">CAREERS</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 12) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  rel="canonical" href="<?php echo $this->basePath(); ?>/admin/career-application">
                   
                                <span class="text-capitalize ">CAREER APPLICATION</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 7) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  rel="canonical" href="<?php echo $this->basePath(); ?>/admin/contact">
                   
                                <span class="text-capitalize ">CONTACT US</span>
                            </a>
                        </li>
                        <li class="nav-item <?php
                                    if (isset($activeTab) && $activeTab == 13) {
                                        echo "active";
                                    }
                                    ?>" >
                            <a class="nav-link"  rel="canonical"  href="<?php echo $this->basePath(); ?>/admin/reset-password">
                   
                                <span class="text-capitalize ">PROFILE</span>
                            </a>
                        </li>
                                              
                                        
                    </ul>
            </div>
            </div>
        </div>
		<div class="main-headers">
		    <nav class="navbar navbar-expand-lg position-fixed" color-on-scroll="500">
                <div class="container-fluid">
                     <div class="logo">
                    <a href="#" class="simple-text">
                        <img src="<?php echo $this->basePath(); ?>/img/footer-logo.png" class="img-fluid">
                        <!--<img src="<?php echo $this->basePath()?>/images/logo.png" class="img-fluid text-center" width="150">-->					
                    </a>
                         
                </div>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">                        
                        <ul class="navbar-nav ml-auto d-flex align-items-center">                           
                            						       
<!--                                <li>
                                    <a href="#">
                                        <span class="img1 ml-2"><img src="<?php echo $this->basePath()?>/images/profile_image.jpg" width="45" height="45" class=" rounded-circle"></span>
                                    </a>
				</li>                                           -->
                                <li class="nav-item dropdown nav-user ml-2">
                                    <a class="nav-link nav-user-img text-dark" id="navbarDropdownMenuLink2" aria-haspopup="true" aria-expanded="false">Admin</a>
                                    <div style="margin-top:-10px">
                                        <a href="<?php echo $this->basePath() ?>/logout" class="log-btn1 ml-2 text-warning">Logout</a>
                                        
                                    </div>
                                </li>
                            
                        </ul>
                    </div>
                </div>
            </nav>
		</div>
        <div class="main-panel">
            <div class="content">
                <div class="">
                    
                    <div class="wrapper ml-auto">
                <div class="main-content">
                    <div class="adminmain-content">
                        <?php echo $this->content; ?>
                    </div>
                    <?php echo $this->inlineScript() ?>
                </div>
            </div> 
                </div>
            </div>         
        </div>
    </div>  
     <div class="feedback-section" id="wTdOl5MnWz">
                <span></span>
            </div>
</body>


</html>
<style>
    .text-color{
        color:black;
    }
    </style>
