<style>.navbar-fluid, .breadcrumb-fluid,.footer-fluid {
display:none;
}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/user/user.css">

<script src="<?php echo $this->basePath(); ?>/js/user/forgot-password.js?v=1"></script>

<div class="container">
    <div class="text-center my-3 mb-lg-4">
        <div class="d-inline-block bg-white">
            <img src="<?php echo $this->basePath(); ?>/img/footer-logo.png" class="img-fluid">
        </div>
    </div>
    <div class="row login-container">
        <div id="forgotPasswordDiv" class="col-12 col-md-6 mx-auto">
            <div class="account-details p-3 p-lg-4 p-xl-5 mb-3">
                <div class="text-center create-account mb-3 mb-lg-4">
                    Forgot your password?
                </div>
                <div class="row mx-0">
                    <div class="col-12 mb-3">
                        <div class="account-text">
                            <label class="text-white text-capitalize">
                                email 
                            </label>
                            <input  id="Zm9yZ290RW1haWxNb2JpbGU" type="text" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" placeholder="Enter Email">
                        </div>
                    </div>
                    <div class="col-12 text-right">

                        <button  id="Zm9yZ290UGFzc3dvcmRTdWJtaXQ" class="btn btn-warning text-uppercase text-center text-dark submit-form w-100">
                            reset password
                        </button>
                        <a href="<?php echo $this->basePath(); ?>/reset-password">

                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div id="verifyOtpDiv" class="col-12 col-md-6 mx-auto d-none">
            <div class="account-details p-3 p-lg-4 p-xl-5 mb-3">
                <div class="text-capitalize text-center create-account mb-3 mb-lg-4">
                    verify OTP
                </div>
                <div class="row mx-0">
                    <div class="col-12 mb-3">
                        <div class="account-text">
                            <label class="text-white text-capitalize">
                                Enter OTP
                            </label>
                            <input  id="verifyOtp" type="text" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" placeholder="Enter 6 digit otp">
                        </div>
                    </div>
                    <div class="col-12 text-right">

                        <button  id="dmVyaWZ5b3Rwc3VibWl0" data-id="0" class="btn btn-warning text-uppercase text-center text-dark submit-form w-100">
                            verify otp
                        </button>
                        <a href="<?php echo $this->basePath(); ?>/reset-password">

                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>