<script src="<?php echo $this->basePath(); ?>/js/admin/delete-career.js"></script>

<div class="d-md-flex justify-content-between align-items-center mb-3">
    <div class="text-capitalize text-dark admin-heading mb-3 mb-md-0">
      Careers
    </div> 
    <div>
         <a href="<?php echo $this->basePath() ?>/admin/add-career-banner"><button class="btn btn-warning add-btn text-dark px-3 px-lg-4">Add Banner</button></a>
         <a href="<?php echo $this->basePath() ?>/admin/add-career"><button class="btn btn-warning add-btn text-dark px-3 px-lg-4 my-2 my-md-">Add Career</button></a>
    </div>
</div>
<div id="page-wrapper">
    <div class="">
        <!-- Page Heading -->
        <div class="table-responsive">

            <table id ="Table" class="table table-striped table-hover border-radius-10">
                <thead>
                    <tr>
                        <th style="width:40px;">S No</th>                        
                         <th>Title</th> 
                         <th>Content</th>
                         <th>Order</th>                                                  
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    <?php $counter = 0;
                    foreach ($careerData as $item) {
                        $counter++ ?>
                        <tr>
                            <td><?php echo $counter; ?></td> 
                            <td class="space-nowrap"><?php echo $item['title']; ?></td>
                            <td class="space-nowrap"><?php echo $item['content']; ?></td>
                            <td class="space-nowrap"><?php echo $item['position_order']; ?></td>
                            <td class="">
                                <div class="d-flex">
                                <span class="add-edit-button mr-2">
                                    <a href="<?php echo $this->basePath() ?>/admin/edit-career?id=<?php echo $item['career_id']; ?>">                                     
                                      <img src="<?php echo $this->basePath()?>/img/edit.png" alt="" style="height:30px">
                                    </a>
                                </span>
                                <span id="deleteCareer" class="" data-id="<?php echo $item['career_id']; ?>" style="cursor:pointer">
                                    <img src="<?php echo $this->basePath()?>/img/delete.png" width="15" alt="" style="height:30px;width:30px">
                                </span>
                                </div>
                            </td>
                        </tr>
                    <?php }
                    ?>
                </tbody>
            </table>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
