<script src="<?php echo $this->basePath(); ?>/js/admin/delete-home-banner.js"></script>
<style>
    #delete_home_banner{
        cursor:pointer;
    }
</style>
<div class="d-md-flex justify-content-between align-items-center mb-3">
    <div class="text-capitalize text-dark admin-heading mb-3 mb-md-0">
        Contact Us Details
    </div> 
    <div>
        <a href="<?php echo $this->basePath() ?>/admin/add-contact-banner"><button class="btn btn-warning add-btn text-dark px-3 px-lg-4">Add Banner</button></a>
        <a href="<?php echo $this->basePath() ?>/admin/add-address"><button class="btn btn-warning add-btn text-dark px-3 px-lg-4">Add Address</button></a>
        
    </div>
</div>
<div id="page-wrapper">
    <div class="">
        <!-- Page Heading -->
        <div class="table-responsive">

            <table id ="Table" class="table  table-hover border-radius-10">
                <thead>
                    <tr>
                        <th style="width: 50px;">S No</th>
                        <th>Name</th>
                        <th>Email</th>                          
                        <th>Mobile</th>
                        <th>Subject</th>
                        <th>Message</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $counter = 0;
                    foreach ($contactQuery as $item) {
                        $counter++
                        ?>
                        <tr>
                            <td><?php echo $counter; ?></td> 
                            <td class="space-nowrap"><?php echo $item['name']; ?></td>
                            <td class="space-nowrap"><?php echo $item['email']; ?></td>
                            <td class="space-nowrap"><?php echo $item['mobile']; ?></td>
                            <td class="space-nowrap"><?php echo $item['subject']; ?></td>
                            <td class="space-nowrap"><?php echo $item['message']; ?></td>
                            
<?php }
?>
                </tbody>
            </table>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
