
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-career.js"></script>
<script src="<?php echo $this->basePath(); ?>/vendor/tinymce/tinymce.min.js"></script>

<style>   
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
</style>
<div class="admin">
    <div class="mb-3 pagesection-name text-dark admin-heading">
        <a href="<?php echo $this->basePath(); ?>/admin/career">
            <img src="<?php echo $this->basePath(); ?>/img/left-arrow.jpg" class="mb-2 img-fluid" style="width: 25px;">
        </a> Edit Career</div>
         
    </div>

<div class="row m-0">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-9 bg-white p-4">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0">
                    <div class="form-group">
                        <label for="editCareerTitle">Title</label>
                        <div class="">
                            <input type="text" value="<?php echo $careerData['title'];?>" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" id="editCareerTitle" placeholder="Enter the title">
                        </div>
                    </div>
                </div>
                
                <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0">
                    <div class="form-group">
                        <label for="editCareerContent">Description</label>
                        <div class="">
                            <textarea type="text" rows="10" class=" border rounded btn-outline-0 px-3 py-2 w-100" id="editCareerContent"><?php echo $careerData['content'];?></textarea>
                        </div>
                    </div>                   
                </div>
                <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0">
                    <div class="form-group">
                        <label for="editCareerOrder">Order</label>
                        <div class="">
                            <input type="number" value="<?php echo $careerData['order'];?>" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" id="editCareerOrder" placeholder="Enter the Order" min="0">
                        </div>
                    </div>
                </div>
                </div>               
                <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0 p-0">
                    <div class="form-group">
                        <div class="text-right">
                            <button type="submit" data-id ="<?php echo $careerData['career_id']; ?>" id="editCareer" class="btn btn-warning submit-btn text-dark px-3 px-lg-4">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

