
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-figure.js"></script>
<script src="<?php echo $this->basePath(); ?>/vendor/tinymce/tinymce.min.js"></script>

<style>   
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
</style>
<div class="admin">
    <div class="mb-3 pagesection-name text-dark admin-heading">
       <a href="<?php echo $this->basePath(); ?>/admin/statistics">
            <img src="<?php echo $this->basePath(); ?>/img/left-arrow.jpg" class="mb-2 img-fluid" style="width: 25px;">
        </a> Edit Figures
    </div> 
    <div class="row m-0">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-9 bg-white p-4">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0">
                    <div class="form-group">
                        <label for="editGeographicalAreasTitle">Geographical Areas</label>
                        <div class="">
                            <input type="text" value="<?php echo $statisticsData['geographical_areas']; ?>" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" id="editGeographicalAreas" placeholder="Enter the geographical areas">
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0">
                    <div class="form-group">
                        <label for="editMarketCoverageTitle">Market Coverage</label>
                        <div class="">
                            <input type="text" value="<?php echo $statisticsData['market_coverage']; ?>" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" id="editMarketCoverage" placeholder="Enter the market coverage">
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0">
                    <div class="form-group">
                        <label for="editMonthlySupplyTitle">Monthly Supply</label>
                        <div class="">
                            <input type="text" value="<?php echo $statisticsData['monthly_supply']; ?>" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" id="editMonthlySupply" placeholder="Enter the monthly supply">
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0">
                    <div class="form-group">
                        <label for="editActiveClient">Active Clients</label>
                        <div class="">
                            <input type="text" value="<?php echo $statisticsData['active_clients']; ?>" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" id="editActiveClient" placeholder="Enter the active clients">
                        </div>
                    </div>
                </div>
                              
            </div> 
            
            <div class="col-12 col-sm-12 col-md-12 mb-3 mb-md-0">
                <div class="form-group">
                    <div class="text-right">
                        <button type="submit" data-id="<?php echo $statisticsData['id']; ?>" id="editStatistic" class="btn btn-warning submit-btn text-dark px-3 px-lg-4">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

