<!-- <script src="<?php echo $this->basePath(); ?>/js/admin/delete-statics.js"></script> -->

<div class="d-md-flex justify-content-between align-items-center mb-3">
    <div class="text-capitalize text-dark admin-heading mb-3 mb-md-0">
       Figures
    </div> 
    <!-- <div>
         <a href="<?php echo $this->basePath() ?>/admin/add-statistics-heading"><button class="btn btn-warning add-btn text-dark px-3 px-lg-4">Heading</button></a>
         <a href="<?php echo $this->basePath() ?>/admin/add-statistics"><button class="btn btn-warning add-btn text-dark px-3 px-lg-4 my-2 my-md-" class="my-2 my-md-0"> Add Statistics</button></a>
        
    </div> -->
</div>
<div id="page-wrapper">
    <div class="">
        <!-- Page Heading -->
        <div class="table-responsive">

            <table id ="Table" class="table table-hover border-radius-10">
                <thead>
                    <tr>
                        <th>Market Coverage</th>
                        <th>Geographical Areas</th>   
                        <th>Monthly Supply</th>         
                        <th>Active Clients</th>                           
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($statistic as $item) {
                        ?>
                        <tr>
                           
                            <td class="space-nowrap"><?php echo $item['market_coverage']; ?></td>
                            <td class="space-nowrap"><?php echo $item['geographical_areas']; ?></td>
                            <td class="space-nowrap"><?php echo $item['monthly_supply']; ?></td>
                            <td class="space-nowrap"><?php echo $item['active_clients']; ?></td>
                      
                            <td class="">
                                <div class="d-flex">
                                <span class="add-edit-button mr-2">
                                    <a href="<?php echo $this->basePath() ?>/admin/edit-figure?id=<?php echo $item['id']; ?>">                                     
                                      <img src="<?php echo $this->basePath()?>/img/edit.png" alt="" style="height:30px">
                                    </a>
                                </span>
                                 
                                </div>
                            </td>
                        </tr>
                    <?php }
                    ?>
                </tbody>
            </table>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
