<script src="<?php echo $this->basePath(); ?>/js/admin/delete-our-team.js"></script>

<div class="d-md-flex justify-content-between align-items-center mb-3">
    <div class="text-capitalize text-dark admin-heading mb-3 mb-md-0">
        Our Team
    </div> 
    <div>
        <a href="<?php echo $this->basePath() ?>/admin/add-our-team"><button class="btn btn-warning add-btn text-dark px-3 px-lg-4">Add Our Team</button></a>

    </div>
</div>
<div id="page-wrapper">
    <div class="">
        <!-- Page Heading -->
        <div class="table-responsive">

            <table id ="Table" class="table table-striped table-hover border-radius-10">
                <thead>
                    <tr>
                        <th>S.No</th>
                        <th>Name</th>
                        <th>Designation</th>                           
                        <th>Image</th>
                        <th>Order</th>                           
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    <?php
                    $counter = 0;
                    foreach ($teamData as $item) {
                        $counter++
                        ?>
                        <tr>
                            <td><?php echo $counter; ?></td> 
                            <td class="space-nowrap"><?php echo $item['name']; ?></td>
                            <td class="space-nowrap"><?php echo $item['designation']; ?></td>

                            <td>
                                <div class="rounded p-0" style="background: url('<?php echo $this->basePath() . "/data/images/" . $item['image_path'] ?>') no-repeat center / cover;height: 60px;width: 60px"></div>
                            </td> 
                            <td class="space-nowrap"><?php echo $item['position_order']; ?></td>
                            <td class="">
                                <div class="d-flex">
                                    <span class="add-edit-button mr-2">
                                        <a href="<?php echo $this->basePath() ?>/admin/edit-our-team?id=<?php echo $item['team_id']; ?>">                                     
                                            <img src="<?php echo $this->basePath() ?>/img/edit.png" alt="" style="height:30px">
                                        </a>
                                    </span>
                                    <span id="deleteourTeam" class="" data-id="<?php echo $item['team_id']; ?>" style="cursor:pointer">
                                        <img src="<?php echo $this->basePath() ?>/img/delete.png" width="15" alt="" style="height:30px;width:30px">
                                    </span>
                                </div>
                            </td>
                        </tr>
<?php }
?>
                </tbody>
            </table>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>

