<style>.navbar-fluid, .breadcrumb-fluid,.footer-fluid {
display:none;
}
</style>
<script src="<?php echo $this->basePath(); ?>/js/admin/reset-password.js?v=1"></script>

<div class="container">
    
     <div class="row login-container">
    <div class="col-12 col-md-6 mx-auto">
        <div class="account-details p-3 p-lg-4 mb-3">
            <div class="text-capitalize text-center create-account mb-3 mb-lg-4">
                 reset password
            </div>
            <div class="row mx-0">
                <div class="col-12 mb-3">
                    <div class="account-text">
                        <label class="text-dark text-capitalize">
                            user name
                        </label>
                        <input  type="text" value="<?php echo $userData['name'];?>" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" disabled>
                    </div>
                </div>
                <div class="col-12 mb-3">
                    <div class="account-text">
                        <label class="text-dark text-capitalize">
                            user email
                        </label>
                        <input  type="text" value="<?php echo $userData['email'];?>" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" disabled>
                    </div>
                </div>
                <div class="col-12 mb-3">
                    <div class="account-text">
                        <label class="text-dark text-capitalize">
                            new password
                        </label>
                        <input id="bmV3UGFzc3dvcmQ"  type="password" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" placeholder="New Password">
                    </div>
                </div>
                <div class="col-12 mb-3">
                    <div class="account-text">
                        <label class="text-dark text-capitalize">
                            Confirm Password
                        </label>
                        <input id="Y29uZmlybVBhc3N3b3Jk" type="password" class="form-control border rounded btn-outline-0 px-3 py-2 w-100" placeholder="Confirm Password">
                    </div>
                </div>
                <div class="col-12 text-right">
                        <button id="Y2hhbmdlUGFzc3dvcmRTdWJta" class="btn btn-warning text-uppercase text-center text-dark submit-form w-100">
                            submit
                        </button>
                </div>
            </div>
        </div>
        <div class="my-2 text-capitalize text-white back-text">
            <a style="color:inherit;" href="<?php echo $this->basePath();?>/login" class="">
                <!--<img src="<?php echo $this->basePath();?>/img/left-arrow.png" style="width: 20px;" class="mr-2">-->
                <!--back to login-->
            </a>



        </div>
    </div>
     </div>
</div>