




<div class="container-fluid mt-4">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 bg-transparent">
                <li class="breadcrumb-item"><a href="<?php echo $this->basePath(); ?>/">Home</a></li>
                <li class="breadcrumb-item active">Blogs</li>
            </ol>
        </nav>
    </div>
</div>

<div class="container-fluid mb-5 bg-white">
    <div class="container">
        <div class="raleway-bold color-000 blogs-name mb-4">
            <h1>Blogs</h1>
        </div>
        <div class="">
            <div class="blog-singleimg mb-3">
                <div style="background: url('<?php echo $this->basePath() . "/data/images/" . $blogData['image_path'] ?>') no-repeat center / cover;">
                </div>
                <!--<img src="<?php echo $this->basePath() . "/data/images/" . $blogData['image_path'] ?>" class="img-fluid" style="height: 270px;width:1103px">-->
            </div>
            <div class="p-3 p-lg-4">
                <div class="jost-medium color-green mb-2">
                    <?php echo $blogData['date']; ?>
                </div>
                <div class="raleway-semibold color-000 blog-singleheading mb-2">
                    <?php echo $blogData['title']; ?>
                </div>
                <div class="color-333 mb-3">
                    <p><?php echo $blogData['content']; ?></p>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

    });
</script>