<style>
    @media only screen and (min-width: 1200px) {
        .careers-fluid::after {
            background-image: url('<?php echo $this->basePath() . "/data/images/" . $careerBanner[0]['image_path'] ?>');
        }
    }
    </style>






<div class="container-fluid breadcrumb-fluid careers-fluid pt-5">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 mb-5 my-lg-5">
                <div class="raleway-bold color-000 page-name mb-2">
                    <?php echo $careerBanner[0]['title'];?>
                </div>
                <div class="color-444">
                    <?php echo $careerBanner[0]['sub_title'];?>
                </div>
            </div>
            <div class="col-12 col-lg-6 d-lg-none">
                <div class="text-right">
                    <img src="<?php echo $this->basePath(); ?>/img/careers-img.png" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid py-5">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-10 mx-auto mb-5">
                <div class="raleway-medium color-000 services-heading mb-4">
                    <h1>Open Positions</h1>
                </div>
                <?php 
                foreach($careerData as $items){?>
                    <div class="careers-box d-md-flex align-items-center justify-content-between mb-4 wow animate__animated animate__fadeInUp">
                    <div class="raleway-semibold color-000 careers-name mb-3 mb-md-0">
                        <?php echo $items['title'];?>
                    </div>
                    <div class="d-block d-md-inline-block text-right">
                        <a href="<?php echo $this->basePath(); ?>/careers-single?id=<?php echo $items['career_id']; ?>" class="btn apply-btn raleway-semibold px-3 stretched-link">
                            Apply
                        </a>
                    </div>
                </div>
               <?php }
                ?>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

    });
</script>