<style>
    .heading_color{
        color:#bf095d;
    }
</style>
<div class="container">
            <h3 class="mb-5 mt-3" style="text-align: center">FAQ</h3>





            <p class="heading_color">1. How to place orders in Qwipo App?</p>
            <p>You can compare the prices of a single item with multiple vendors and then choose what's best for you.
                You can add the selected item to the cart and then confirm the order. Order once confirmed you can pay
                the amount through payment gateways or pay with cash when the items are delivered to your doorstep.

            </p>
            <p class="heading_color">2. How to place a Return request?

            </p>
            <p>If you are not satisfied with the quality, contents, or condition of (a) product(s), you can simply raise
                a request with our customer support team within 24 hours of purchase or delivery to initiate the return
                of the items. The items will be picked up from you within 3-7 days post the return request has been
                accepted.</p>

            <p class="heading_color">3. How will the refund amount be credited?</p>
            <p>Once your return request has been accepted, and the return items have been picked up, it takes 24
                business hours to process the refund amount. Refunds will be processed using the same payment gateway
                with which the payment was received.</p>



            <p class="heading_color">4. Can we modify the order once it's placed?</p>
            <p>If you wish to modify the order placed by you, you may do so by calling our customer care team and revise
                your order accordingly.</p>


            <p class="heading_color">5. How can we cancel the order after it's placed?

            </p>
            <p>If you want to cancel the order, you may do so in the app before dispatch of the items, or please call us
                on 9121222836 or drop an email at info@qwipo.com (Sun to Sat – 6 am to 8 pm), and we will help you in
                cancelling the order. You may as well cancel the order at your doorstep.

            </p>



















        </div>