<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/jquery.fancybox.min.css">












<div class="container-fluid mt-4">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-0 bg-transparent">
                <li class="breadcrumb-item"><a href="<?php echo $this->basePath(); ?>/">Home</a></li>
                <li class="breadcrumb-item active">Gallery</li>
            </ol>
        </nav>
    </div>
</div>

<div class="container-fluid mb-5 bg-white">
    <div class="container">
        <div class="row mx-n2">
            <?php foreach ($gallery as $item) { ?>
                <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3  mb-4 px-2 wow animate__animated animate__fadeInUp">
                    <div class="gallery-box">
                        <a data-fancybox="gallery" href="<?php echo $this->basePath() . "/data/images/" . $item['image_path'] ?>">
                            <img src="<?php echo $this->basePath() . "/data/images/" . $item['image_path'] ?>" style="height:300px;object-fit: contain">
                        </a>
                    </div>
                </div>
            <?php }
            ?>


        </div>
    </div>
</div>

<script src="<?php echo $this->basePath(); ?>/js/jquery.fancybox.min.js"></script>

<script>
    $(document).ready(function () {
        $('[data-fancybox="gallery"]').fancybox({
            // Options will go here
            protect: true,
            loop: true,
            transitionEffect: "slide",
            transitionDuration: 366
            
        });
    });
</script>