<style>
    .heading_color{
        color:#bf095d;
    }
</style>
<div class="container">
            <h3 class="mb-5 mt-3" style="text-align: center">RETURN, EXCHANGE, REFUND, ORDER MODIFICATION AND ORDER
                CANCELLATION POLICY</h3>

            <p>It is our ultimate attempt to provide you with exemplary products creating the best experience intended
                at the time of your purchase.</p>
            <p>However, in the uneventful scenario that you need to return our products, returns shall be governed by
                the following policies:

            </p>


            <p class="heading_color">Return and Exchange:

            </p>
            <p>1. Due to our quality, purity and hygiene commitments and standards, for goods once sold or delivery
                accepted, we shall not be able to accept return or exchange of open, missing contents or damaged
                products.</p>

            <p>2. If you are not satisfied with the quality, contents or condition of (a) product(s), you can simply
                raise a request with our customer support team within 24 hours of purchase or delivery to initiate
                return of the items. The items will be picked up from you within 3-7 days post the return request has
                been accepted.</p>
            <p>3. Goods shall be eligible for return only within 3 days from the date of purchase/ delivery. Please note
                that exchange/ return/ refund cannot be done partly for any order.</p>

            <p>4. Exchange of products is not applicable.</p>



            <p class="heading_color">Refund</p>
            <p>5. Once your return/refund request has been accepted, the process shall be completed within 24 business
                hrs. Refunds will be processed using the same payment gateway with which the payment was received.</p>


            <p class="heading_color">Order Modification:

            </p>
            <p>6. If you wish to modify the order placed by you, you may do so by calling our customer care team and
                revise your order accordingly.

            </p>
            <p class="heading_color">Order Cancellation:

            </p>
            <p>7. If you want to cancel the order, you may do so in the app before dispatch of the items, or please call
                us on 9121222836 or drop an email at info@qwipo.com (Sun to Sat – 6 am to 8 pm), and we will help you in
                cancelling the order. You may as well cancel the order at your doorstep.

            </p>
            <p>**QWIPO reserves the right to cancel any order without pre-confirming the customer at any time and may
                verify any order before shipping the same to the customer that may include having a verbal or written
                confirmation from the customer.
                Note – Orders can be only cancelled till the status is “Processing”.

            </p>
















        </div>